# This workflow will build a MuleSoft project and deploy to CloudHub

name: Custom - Deploy to QA

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      env:
        ANYPOINT_EROAD_USERNAME: ${{ secrets.ANYPOINT_EROAD_USERNAME }}
        ANYPOINT_EROAD_PASSWORD: ${{ secrets.ANYPOINT_EROAD_PASSWORD }}
        ENC_KEY: ${{ secrets.ENC_KEY }}
      run: |
        bash ./scripts/configure-maven.sh
        mvn -B package --file pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: target/*.jar          
    - uses: actions/download-artifact@master
      with:
        name: artifacts
  deploy-qa:
    runs-on: ubuntu-latest 
    needs: build
    environment: qa
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to CloudHub
      env:
        ANYPOINT_EROAD_USERNAME: ${{ secrets.ANYPOINT_EROAD_USERNAME }}
        ANYPOINT_EROAD_PASSWORD: ${{ secrets.ANYPOINT_EROAD_PASSWORD }}
        ENC_KEY: ${{ secrets.ENC_KEY }}
      run: |
        mvn package deploy -P cloudhub -DmuleDeploy -Denv=QA -Danypoint.env=qa -Denc.key=$ENC_KEY -Danypoint.username=$ANYPOINT_EROAD_USERNAME -Danypoint.password=$ANYPOINT_EROAD_PASSWORD -Dsumo.server=$sumo_server_qa
